repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: python
    types: [python]
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [python]
    args: ["--ignore-missing-imports", "--scripts-are-modules"]
  - id: flake8
    name: flake8
    entry: flake8
    language: python
    types: [python]
  - id: isort
    name: isort
    entry: isort
    language: python
    types: [python]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-toml
  - id: check-yaml
- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
    - id: docformatter
      args: [--in-place]